export const ADD_STUDENT = "ADD_STUDENT";
export const EDIT_STUDENT = "EDIT_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const ADD_TEACHER = "ADD_TEACHER";
export const EDIT_TEACHER = "EDIT_TEACHER";
export const DELETE_TEACHER = "DELETE_TEACHER";
